# action.yaml
name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
inputs:
  pokemon_id:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: 1

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.pokemon_id }}"