# action.yaml
name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
inputs:
  pokemon_id:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: 1

runs-on: ubuntu-latest
  steps:
    - run: |
      echo "Env: ${{ inputs.task_name}}"
